### ISSUE TITLE
🛠 Self-register bitcoin validator for Oraichain's validators

### ISSUE THREAD

**Issue by perfogic** [oraichain/cw-bitcoin#9]
## Overview

- This issue will enhance the native decentralized ability inside cw-bitcoin, since registering validators will not depend on the operation team.
- However, the size of bitcoin contract is too large right now (792KB) which is near the maximum default size of wasm contract in wasm module. Therefore

## Tasks

- [x] Divide cw-bitcoin contract to reduce size
    + [x] Develop light client contract
    + [x] Integrate light client contract to cw bitcoin
- [x] Implement native validator registration mechanism
